# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 4.0"

gem "gyoku", "~> 1.4"

gem "sinatra-subdomain", "~> 0.4.0"

gem "sinatra-contrib", "~> 4.0"

gem "rack", "~> 3.1"
